version: '2'
services:
    registry:
        image: jhipster/jhipster-registry:v3.2.4
        volumes:
            - ./central-server-config:/central-config
        environment:
            - SPRING_PROFILES_ACTIVE=dev,native
            - SECURITY_USER_PASSWORD=admin
            - REGISTRY_PASSWORD=admin
            # - GIT_URI=XXXXXX
            # - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761
